---
title: "Vectorizer"
author: "Adrian Tame"
date: '2022-05-12'
output: html_document
---

```{r}
if(!require(wordVectors)){
  devtools::install_github("bmschmidt/wordVectors")
}

library(wordVectors)
library(tidyverse)

setwd("~/Documents/Repositories/CRAN_Search_Engine")
```

```{r}
packages <- read.csv("~/Documents/Repositories/CRAN_Search_Engine/data/packages_11_may_2022.csv")


normalizar <- function(texto, vocab = NULL){
  # minúsculas
  texto <- tolower(texto)
  # varios ajustes
  texto <- gsub("\\s+", " ", texto)
  texto <- gsub("\\.[^0-9]", " _punto_ ", texto)
  texto <- gsub(" _s_ $", "", texto)
  texto <- gsub("\\.", " _punto_ ", texto)
  texto <- gsub("[«»¡!¿?-]", "", texto) 
  texto <- gsub(";", " _punto_coma_ ", texto) 
  texto <- gsub("\\:", " _dos_puntos_ ", texto) 
  texto <- gsub("\\,[^0-9]", " _coma_ ", texto)
  texto <- gsub("\\s+", " ", texto)
  texto <- gsub("\\n", "", texto)
  texto
}
periodico_df <- tibble(txt = packages$Description) |>
                mutate(id = row_number()) |>
                mutate(txt = normalizar(txt))
```

```{r}
if(!file.exists('./salidas/noticias_w2v.txt')){
  tmp <- tempfile()
  # tokenización
  write_lines(periodico_df$txt,  tmp)
  prep <- prep_word2vec(tmp, 
          destination = './salidas/noticias_w2v.txt', bundle_ngrams = 2)
  } 
```

```{r}
if (!file.exists("./salidas/noticias_vectors.bin")) {
  modelo <- train_word2vec("./salidas/noticias_w2v.txt", 
          "./salidas/noticias_vectors.bin",
          vectors = 100, threads = 8, window = 4, cbow = 0,  
          iter = 20, negative_samples = 20, min_count = 10) 
} else {
  modelo <- read.vectors("./salidas/noticias_vectors.bin")
}
```

```{r}
vector_gol <- modelo[["map"]] |> as.numeric()
vector_gol
```

```{r}
ejemplos <- modelo |>  closest_to("monte_carlo", n = 5)
ejemplos
```





































